@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":AddressBookParser" as AddressBookParser LOGIC_COLOR
participant ":CreateGroupCommandParser" as CreateGroupCommandParser LOGIC_COLOR
participant "createGroupCommand:CreateGroupCommand" as CreateGroupCommand LOGIC_COLOR
participant ":CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
end box

[-> LogicManager : execute("creategroup gn/GROUP_NAME n/NAME")
activate LogicManager

LogicManager -> AddressBookParser : parseCommand("creategroup gn/GROUP_NAME n/NAME")
activate AddressBookParser

create CreateGroupCommandParser
AddressBookParser -> CreateGroupCommandParser
activate CreateGroupCommandParser

CreateGroupCommandParser --> AddressBookParser
deactivate CreateGroupCommandParser

AddressBookParser -> CreateGroupCommandParser : parse("gn/GROUP_NAME")
activate CreateGroupCommandParser

create CreateGroupCommand
CreateGroupCommandParser -> CreateGroupCommand
activate CreateGroupCommand

CreateGroupCommand --> CreateGroupCommandParser : createGroupCommand
deactivate CreateGroupCommand

CreateGroupCommandParser --> AddressBookParser : createGroupCommand
deactivate CreateGroupCommandParser
'Hidden arrow to position the destroy marker below the end of the activation bar.
CreateGroupCommandParser -[hidden]-> AddressBookParser
destroy CreateGroupCommandParser

AddressBookParser --> LogicManager : createGroupCommand
deactivate AddressBookParser

LogicManager -> CreateGroupCommand : execute()
activate CreateGroupCommand

CreateGroupCommand -> Model : CreateGroup(g:Group)
activate Model

Model --> CreateGroupCommand
deactivate Model

create CommandResult
CreateGroupCommand -> CommandResult
activate CommandResult

CommandResult --> CreateGroupCommand
deactivate CommandResult

CreateGroupCommand --> LogicManager : result
deactivate CreateGroupCommand

[<--LogicManager
deactivate LogicManager
@enduml
