@startuml
start
:User executes command;

'Since the beta syntax does not support placing the condition outside the
'diamond we place it as the true branch instead.

if () then (user is currently viewing ExpensesPage)
    :Check List of Expenses;
    if () then ([INDEX in range (1, length of Expense List)])
    :delete expense in position INDEX from list;
    else ([else])
    endif
else ([else])
endif
stop
@enduml
