@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":AweParser" as AweParser LOGIC_COLOR
participant ":FindGroupsCommandParser" as FindGroupsCommandParser LOGIC_COLOR
participant "d:FindGroupsCommand" as FindGroupsCommand LOGIC_COLOR
participant ":CommandResult" as CommandResult LOGIC_COLOR
participant ":GroupContainsKeywordsPredicate" as GroupContainsKeywordsPredicate LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
end box

[-> LogicManager : execute("findgroups London")
activate LogicManager

LogicManager -> AweParser : parseCommand("findgroups London")
activate AweParser

create FindGroupsCommandParser
AweParser -> FindGroupsCommandParser
activate FindGroupsCommandParser

FindGroupsCommandParser --> AweParser
deactivate FindGroupsCommandParser

AweParser -> FindGroupsCommandParser : parse("London")
activate FindGroupsCommandParser

create GroupContainsKeywordsPredicate
FindGroupsCommandParser -> GroupContainsKeywordsPredicate
activate GroupContainsKeywordsPredicate

GroupContainsKeywordsPredicate -> FindGroupsCommandParser : predicate
deactivate GroupContainsKeywordsPredicate

create FindGroupsCommand
FindGroupsCommandParser -> FindGroupsCommand : predicate
activate FindGroupsCommand

FindGroupsCommand --> FindGroupsCommandParser : command
deactivate FindGroupsCommand

FindGroupsCommandParser --> AweParser : command
deactivate FindGroupsCommandParser
'Hidden arrow to position the destroy marker below the end of the activation bar.
FindGroupsCommandParser -[hidden]-> AweParser
destroy FindGroupsCommandParser

AweParser --> LogicManager : command
deactivate AweParser

LogicManager -> FindGroupsCommand : execute()
activate FindGroupsCommand

FindGroupsCommand -> Model : updateFilteredGroupList(predicate)
activate Model

Model --> FindGroupsCommand
deactivate Model

create CommandResult
FindGroupsCommand -> CommandResult
activate CommandResult

CommandResult --> FindGroupsCommand : result
deactivate CommandResult

FindGroupsCommand --> LogicManager : result
deactivate FindGroupsCommand
'Hidden arrow to position the destroy marker below the end of the activation bar.
FindGroupsCommand -[hidden]-> AweParser
destroy FindGroupsCommand


[<--LogicManager
deactivate LogicManager
@enduml
