@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

Package Model <<Rectangle>>{
Interface ReadOnlyAddressBook <<Interface>>
Interface ReadOnlyUserPrefs <<Interface>>
Interface Model <<Interface>>
Class AddressBook
Class ReadOnlyAddressBook
Class Model
Class ModelManager
Class UserPrefs
Class ReadOnlyUserPrefs
Class UniquePersonList
Class UniqueGroupList
Class ExpenseList

Package Person <<Rectangle>>{
}

Package Group <<Rectangle>>{
}

Package Expense <<Rectangle>>{
}

}



Class HiddenOutside #FFFFFF
HiddenOutside ..> Model

AddressBook ..|> ReadOnlyAddressBook

ModelManager ..|> Model
Model ..> ReadOnlyUserPrefs
Model ..> ReadOnlyAddressBook
ModelManager --> "1" AddressBook
ModelManager --> "1" UserPrefs
UserPrefs ..|> ReadOnlyUserPrefs

AddressBook *--> "1" UniquePersonList
UniquePersonList --> "~* all" Person

AddressBook *--> "1" UniqueGroupList
UniqueGroupList -right-> "~* all" Group
Group --> "1..* members" Person

AddressBook *--> "1" ExpenseList
ExpenseList --> "~* all" Expense
Expense ---> "1 payer" Person
Expense -right--> "1..* involved" Person


ModelManager -->"~* filtered" Person
ModelManager -->"~* filtered" Group
ModelManager -->"~* filtered" Expense
@enduml
