@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

Package Model <<Rectangle>>{
Interface ReadOnlyAwe <<Interface>>
Interface ReadOnlyUserPrefs <<Interface>>
Interface Model <<Interface>>
Class Awe
Class ReadOnlyAwe
Class Model
Class ModelManager
Class UserPrefs
Class ReadOnlyUserPrefs
Class UniqueXYZList
Class ABCList

Package XYZ <<Rectangle>>{
}

Package ABC <<Rectangle>>{
}

note "XYZ = Groups, Person\nABC = Expense, Transaction Summary, Payments \n\nImplementation are referenced below" as n1

}



Class HiddenOutside #FFFFFF
HiddenOutside ..> Model

Awe .up.|> ReadOnlyAwe

ModelManager .up.|> Model
Model .right.> ReadOnlyUserPrefs
Model .left.> ReadOnlyAwe
ModelManager -left-> "1" Awe
ModelManager -right-> "1" UserPrefs
UserPrefs .up.|> ReadOnlyUserPrefs

Awe *--> "1" UniqueXYZList
UniqueXYZList -right-> "~* all" XYZ

Awe *--> "1" ABCList
ABCList --> "~* all" ABC

ModelManager -->"~* filtered" XYZ
ModelManager -->"~* filtered" ABC

ABC .. n1
XYZ .. n1

@enduml
