@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor STORAGE_COLOR
skinparam classBackgroundColor STORAGE_COLOR

package Storage{

package "UserPrefs Storage" #F4F6F6{
Interface UserPrefsStorage <<Interface>>
Class JsonUserPrefsStorage
}

Interface Storage <<Interface>>
Class StorageManager

package "Awe Storage" #F4F6F6{
Interface AweStorage <<Interface>>
Class JsonAweStorage
Class JsonSerializableAwe
Class JsonAdaptedPerson
Class JsonAdaptedTag
Class JsonAdaptedGroup
Class JsonAdaptedExpense
}

}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Storage

StorageManager .up.|> Storage
StorageManager -up-> "1" UserPrefsStorage
StorageManager -up-> "1" AweStorage

Storage -left-|> UserPrefsStorage
Storage -right-|> AweStorage

JsonUserPrefsStorage .up.|> UserPrefsStorage
JsonAweStorage .up.|> AweStorage
JsonAweStorage ..> JsonSerializableAwe
JsonSerializableAwe --> "*" JsonAdaptedPerson
JsonSerializableAwe --> "*" JsonAdaptedGroup
JsonAdaptedPerson --> "*" JsonAdaptedTag
JsonAdaptedGroup --> "*" JsonAdaptedExpense

@enduml
